cluster-manager.namespace-prefix=dev-
cluster-manager.provisioning.mode=namespace
cluster-manager.container-only.namespace=devcontainers
cluster-manager.managed-by=cluster-manager
cluster-manager.label-prefix=cluster-manager.example.com
cluster-manager.devcontainer.image=ubuntu:24.04
cluster-manager.devcontainer.service-account=dev-user
cluster-manager.devcontainer.deployment-name=devcontainer
cluster-manager.devcontainer.service-name=devcontainer
cluster-manager.devcontainer.service-type=ClusterIP
cluster-manager.devcontainer.ssh-host=rp.local
cluster-manager.auth.mode=simple
cluster-manager.kubeconfig.cluster-name=k3s
cluster-manager.kubeconfig.server=https://rp.local:6443
cluster-manager.kubeconfig.insecure-skip-tls-verify=true
cluster-manager.admin-user-ids=alice
cluster-manager.service-account-token.expiration-seconds=3600
%test.cluster-manager.admin-user-ids=alice
quarkus.oidc.enabled=false

quarkus.swagger-ui.always-include=true
