cluster-manager.namespace-prefix=dev-
cluster-manager.managed-by=cluster-manager
cluster-manager.label-prefix=cluster-manager.example.com
cluster-manager.devcontainer.image=ubuntu:24.04
cluster-manager.devcontainer.service-account=dev-user
cluster-manager.devcontainer.deployment-name=devcontainer
cluster-manager.devcontainer.service-name=devcontainer

quarkus.swagger-ui.always-include=true
